#!/bin/sh
SCRIPT=$(readlink -f $0)
SCRIPTPATH=$(dirname $SCRIPT)
cd $SCRIPTPATH/..
rm -r ../irc_client_pages/docs
dartdoc --link-api --out ../irc_client_pages/docs/ --include-lib irc_client lib/irc_client.dart
dartdoc --link-api --out docs --mode static --include-lib irc_client lib/irc_client.dart
